---
title: "tidy_data"
output: html_document
date: "2025-09-23"
---

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

This document will show how to tidy data.

## Pivot Longer

```{r}

pulse_df = 
    read_sas("data_import_examples/public_pulse_data.sas7bdat") |> 
    janitor::clean_names() |> 
    pivot_longer( #makes wide data longer
      cols = bdi_score_bl:bdi_score_12m, #identify columns that are long (have more than one piece of info)
      names_to = "visit",
      values_to = "bdi_score",
      names_prefix = "bdi_score_" #gets rid of prefix in name of variable
    ) |> 
  mutate(visit = replace(visit, visit =="bl", "00m")) |> 
  relocate(id, visit) #put ID before visit as first two variables
      
```

Do one more example.

```{r}
litters_df = 
  read_csv("data_import_examples/FAS_litters.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  pivot_longer(
    cols = gd0_weight:gd18_weight,
    names_to = "gd_time",
    values_to = "weight"
  ) |> 
  mutate(gd_time = case_match(
    gd_time,
    "gd0_weight" ~ 0,
    "gd18_weight" ~ 18
  )) #tell R a list of variables - tell what new name you want to give old variable
```

## Pivot Wider

Sometimes you have long data you want to make wider.

Let's make up an analysis results table.

```{r}

analysis_df = 
  tibble(group = c("treatment", "treatment", "control", "control"),
         time = c("pre", "post", "pre", "post"),
         mean = c(4, 10, 4.2, 5))


```

Pivot wider for human readability

```{r}

analysis_df |> 
  pivot_wider(
    names_from = time,
    values_from = mean
  ) |> 
  knitr::kable() #put into nicer table format for your markdown file
```

## Bind tables

```{r}
#you have multiple tables of a similar structure and you want to stack them together

fellowship_ring = 
  read_excel("data_import_examples/LotR_Words.xlsx", range = "B3:D6") |> 
  mutate(movie = "fellowship_ring")

two_towers = 
  read_excel("data_import_examples/LotR_Words.xlsx", range = "F3:H6") |> 
  mutate(movie = "two_towers")

return_king = 
  read_excel("data_import_examples/LotR_Words.xlsx", range = "J3:L6") |> 
  mutate(movie = "return_king")

#these all have the same variables, let's stack on top of each other

lotr_df = 
  bind_rows(fellowship_ring, two_towers, return_king) |> 
  janitor::clean_names() |> 
  pivot_longer(
    cols = female:male,
    names_to = "sex",
    values_to = "words"
  ) |> 
  relocate(movie) |> 
  mutate(race = str_to_lower(race))

#but you have columns for male and female when you should have a gender variable with male/female values


```

##Join FAS datasets

Import the `litters` dataset.

```{r}
litters_df = 
  read_csv("data_import_examples/FAS_litters.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  mutate(wt_gain = gd18_weight - gd0_weight) |> 
  separate( #tell R variable you want to split up, and what you want it to split into
    group, into = c("dose", "day_of_treatment"), sep = 3 #split after the 3rd character (or you could say split        after a comma)
  )
  
```

Import `pup` next!

```{r}
pups_df = 
  read_csv("data_import_examples/FAS_pups.csv", skip = 3, na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  mutate(sex = case_match(
    sex, #tell whcih variable to look at
    1 ~ "male",
    2 ~ "female"
  )
  )
```

Join the datasets!

```{r}

fas_df = 
  left_join(pups_df, litters_df, by = "litter_number") |> #prioritize pups_df. add to it info from litter. lose things from litter that don't match up with something from pups
  relocate(litter_number, dose, day_of_treatment)
  
```





